services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qc-api-v2
    restart: always
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:12345@postgres:5432/postgres
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: qc-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

